### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by ericmjonas**
Thanks to tremendous work done by @washcycle we now have python3 support ! It took quite a while to get things up and working and there are a lot of tiny commits here, esp. since I was doing too much of the debugging through TravisCI and I had to change the way build scripts were handled. 

Major changes:
1. We now json-encode the function instead of pickling it, so that it can be decoded by both the lambda runtime (python 2.7) as well as the python3 jobrunner. The resulting base64 encoding makes this a bit bigger than I'd otherwise like it to be, but that's a future optimization. 

2. I don't really care about ascii vs utf encoding of various strings, and mashed the keyboard a bit to get things working. So @washcycle if you have strong opinions on bytes and character encodings, I'd love some advice. 

3. The import situation is a bit of a mess. In particular the way the lambda runner invokes the handler appears incompatible with `from __future__ import absolute_import`. 

@washcycle I'd love your feedback on this and for you to try it out! Note that you'll probably want to blow away and setup your `~/.pywren_config`.

### CODE REVIEW

**Comment by washcycle** [comment]
I'm trying to test this and maybe the issue will jump out to you.
```
(data-sci) hiro@deathscythe /data/Development/python/py3/pywren $ python examples/simpletest.py
2017-02-13 20:56:20,238 [INFO] pywren.wren: map de6b1a45-993a-41bf-a917-9407ce87d516 00000 apply async
2017-02-13 20:56:20,238 [INFO] pywren.wren: call_async de6b1a45-993a-41bf-a917-9407ce87d516 00000 lambda invoke 
2017-02-13 20:56:20,717 [INFO] pywren.wren: call_async de6b1a45-993a-41bf-a917-9407ce87d516 00000 lambda invoke complete
2017-02-13 20:56:20,799 [INFO] pywren.wren: map invoked de6b1a45-993a-41bf-a917-9407ce87d516 00000 pool join
de6b1a45-993a-41bf-a917-9407ce87d516
2017-02-13 20:56:37,650 [INFO] pywren.wren: ResponseFuture.result() de6b1a45-993a-41bf-a917-9407ce87d516 00000 call_success False
Traceback (most recent call last):
  File "examples/simpletest.py", line 24, in <module>
    res = fut.result() 
  File "/home/hiro/Development/anaconda3/envs/data-sci/lib/python3.5/site-packages/pywren-0.0.9-py3.5.egg/pywren/wren.py", line 549, in result
    reraise(*self._traceback)
  File "/home/hiro/Development/anaconda3/envs/data-sci/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/task/jobrunner.py", line 22, in <module>
  File "/tmp/pymodules/pywren/__init__.py", line 2, in <module>
  File "/tmp/pymodules/pywren/wren.py", line 19, in <module>
ImportError: No module named 'glob2'
```

I double checked my 3.5 version and it has glob2, do you think this is being returned from the runtime?

**Comment by ericmjonas** [comment]
Awesome, what version of the runtime are you using? (what's the S3 key?)
and did you run `pywren deploy_lambda` ?

**Comment by washcycle** [comment]
```
runtime:
    s3_bucket: ericmjonas-public
    s3_key: condaruntime.python3.stripped.scipy-cvxpy-sklearn.mkl_avx2.tar.gz
```

I did run `pywren deploy_lambda` is there a way to confirm it got deployed right. I'll see if I can confirm it worked. ...5 minutes later.. I'm digging around on AWS, mind you this is the first time i've messed with the Lambda service. It doesn't look like anything has been deployed assuming I'm looking in the right spot.

**Comment by ericmjonas** [comment]
Ok, can you see any logs at the URL returned from `pywren log_url`?

**Comment by washcycle** [comment]
Checked the `log_url` no logs were created.

**Comment by ericmjonas** [comment]
Ok, great. First, do you know if your account is an IAM account or is a
standard AWS root account?
Second, would you be willing to paste your ~/.pywren_config ? I think the
only possibly sensitive data there is the account iD, so you can remove
that.

**Comment by washcycle** [comment]
It is an IAM account.

```
account:
    aws_account_id: XXXXXXXXXXXX
    aws_lambda_role: pywren_exec_role
    aws_region: us-east-1

lambda:
    memory : 1536
    timeout : 300
    function_name : pywren1

s3:
    bucket: pywern
    pywren_prefix: pywren.jobs

runtime:
    s3_bucket: ericmjonas-public
    s3_key: condaruntime.python3.stripped.scipy-cvxpy-sklearn.mkl_avx2.tar.gz

standalone:
    ec2_instance_type: m4.4xlarge
    sqs_queue_name: pywren-queue
    visibility: 10
    ec2_ssh_key : ec2-us-west-2
    target_ami : ami-b04e92d0
    instance_name: pywren-standalone
    instance_profile_name: pywren-standalone
    max_idle_time: 60
    idle_terminate_granularity: 3600
```

I can see the pywren1 in the lambda function listing now too. I bet it is something small like a permissions issue on AWS or some config zombie. I can try cloning this at work tomorrow to see if I get the same issue.

**Comment by ericmjonas** [comment]
can you set `PYWREN_LOGLEVEL=DEBUG` and then run your script and try
putting the output in a gist? I'm curious if there's interesting data
there.

**Comment by washcycle** [comment]
My second comment above it with `PYWREN_LOGLEVEL=DEBUG`. Going to table this for now. I might examine the travis builds and try to mimic that when I get to work tomorrow. Thanks for the help.

**Comment by ericmjonas** [comment]
Wow it looks like I might have actually broken the runtime with my latest
build. Ugh, I'm sorry, this is 100% my fault

**Comment by washcycle** [comment]
I tested it and it is working now!!! Awesome! Saw your AMA on reddit too interesting topic!

**Pull request merged**
