### PR TITLE
My cPickle imports cross compatible

### PR DESCRIPTION
**Pull request by tdhopper**

### CODE REVIEW

**Comment by ericmjonas** [comment]
I'm seeing some syntax errors on the travis build, can you check that? 
Also I'm not sure the travis build stuff will ever work due to encrypted keys in the .yaml but we can see :)

**Comment by tdhopper** [comment]
Ha. I see I shouldn't submit untested PRs on my lunchbreak. 

I'll see if I can make some time to step back and see about adding more robust Python3 support.

**Comment by ericmjonas** [comment]
Ok so now it's failing because of the dumb travis creds thing. If I made you a collaborator on the repo would you be willing to update the pull req there? Also I'm cleaning things up a bit for a more sincere python 2,3 interop game

**Comment by tdhopper** [comment]
@ericmjonas Happy to be a collaborator as long as the expectations for me stay low :)

**Comment by ericmjonas** [comment]
This is also fixed !

**Pull request closed without merging**
