### PR TITLE
Make imports Python 2/3 cross-compatible

### PR DESCRIPTION
**Pull request by tdhopper**

### CODE REVIEW

**Comment by ericmjonas** [comment]
@tdhopper I think currently my python3 situation is abysmal. Including the fact that the packaged runtimes I'm using take a 2.7x anaconda. Are you mostly a python3 user now?

**Comment by tdhopper** [comment]
@ericmjonas It's my default. Still using 2 for a lot at work though.

**Comment by tdhopper** [comment]
I forgot Lambda doesn't even have 3 support...

**Comment by ericmjonas** [comment]
If there's boto support for python3 that's not an issue, because I download a conda tarball and everything runs inside that.

**Comment by tdhopper** [comment]
Oh, clever!

**Comment by ericmjonas** [comment]
@tdhopper This works now! Closing PR

**Pull request closed without merging**
